name: Java CI with Maven - Process & Tools - Challenge 2

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # ms-accounts
      - name: Grant execute permission for mvnw
        working-directory: ./ms-accounts
        run: chmod +x mvnw

      - name: Build with Maven
        working-directory: ./ms-accounts
        run: ./mvnw test

      # ms-persons
      - name: Grant execute permission for mvnw
        working-directory: ./ms-persons
        run: chmod +x mvnw

      - name: Build with Maven
        working-directory: ./ms-persons
        run: ./mvnw test